jwt:
  secret: f17155e9e7fcf6b8671d573b93f65b60ddb02b660d5d131c041246376a91a1b970145a8afb3c94ab10e4e3f5ef7171cbc70d6491f382a7d2f27b93aa148a566a

server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081 ##http://user-service:8081
          predicates:
            - Path=/api/users/**,/Path=/api/cuenta/**